version: '3.3'
services:
  solr:
    image: "solr:8.4.1"
    ports:
     - "8983:8983"

    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - semantix
  nutch:
    image: "apache/nutch:release-1.16"
    links:
      - solr
    environment: 
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    working_dir: /root/nutch
    command: '/root/nutch/bin/crawl -i -D solr.server.url=http://solr:8983/solr/semantix -s urls crawl 5'
    volumes:
        - ./nutch/index-writers.xml:/root/nutch/conf/index-writers.xml
        - ./nutch/nutch-site.xml:/root/nutch/conf/nutch-site.xml
        - ./nutch/regex-urlfilter.txt:/root/nutch/conf/regex-urlfilter.txt
        - ./nutch/seed.txt:/root/nutch/urls/seed.txt
        - ./nutch/schema.xml:/root/nutch/conf/schema.xml
